# Copyright 2026 Snowflake, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# config.py

import pandas as pd

# --- Application Version ---
APP_VERSION = "v2.1.1"

# Fallback sample data for UI development when not connected or on error
SAMPLE_WAREHOUSE_LIST_FOR_UI = ["DEV_WH_SAMPLE", "PROD_BI_WH_SAMPLE", "ETL_WH_SAMPLE"]
SAMPLE_OUTPUT_COLUMNS = [
    'WAREHOUSE_NAME', 'WAREHOUSE_TSHIRT_SIZE_CONFIG', 'MIN_CLUSTER_COUNT',
    'MAX_CLUSTER_COUNT', 'SCALING_POLICY', 'AUTO_SUSPEND_SECONDS',
    'AUTO_RESUME_ENABLED', 'QAS_ENABLED', 'QAS_MAX_SCALE_FACTOR',
    'PERIOD_TOTAL_CREDITS_CALCULATED',
    'WAREHOUSE_DETAILS_JSON'
]
SAMPLE_JSON_OUTPUT_DF = pd.DataFrame(columns=SAMPLE_OUTPUT_COLUMNS) # Empty DF with schema
# You can populate SAMPLE_JSON_OUTPUT_DF with a sample row if needed for extensive local UI testing
# For example:
# SAMPLE_JSON_OUTPUT_DF_WITH_ROW = pd.DataFrame([{
#     'WAREHOUSE_NAME': 'SAMPLE_WH',
#     'WAREHOUSE_TSHIRT_SIZE_CONFIG': 'Medium', 'MIN_CLUSTER_COUNT': 1, 'MAX_CLUSTER_COUNT': 2, 'SCALING_POLICY': 'STANDARD',
#     'AUTO_SUSPEND_SECONDS': 600, 'AUTO_RESUME_ENABLED': True, 'QAS_ENABLED': False, 'QAS_MAX_SCALE_FACTOR': 8,
#     'WAREHOUSE_DETAILS_JSON': '{"properties": {"WAREHOUSE_TSHIRT_SIZE_CONFIG": "Medium", ...}, "hourly_info": [{"USAGE_HOUR_UTC": "2025-05-19T10:00:00Z", ...}]}'
# }])


# Cortex Model Configuration - Only Claude models supported
AVAILABLE_CORTEX_MODELS = ["claude-3-7-sonnet", "claude-4-sonnet"]
DEFAULT_CORTEX_MODEL = "claude-3-7-sonnet"

# Cortex model token limits (verified from Snowflake docs)
CORTEX_MODEL_TOKEN_LIMITS = {
    "claude-3-7-sonnet": 200000,
    "claude-4-sonnet": 200000,
}

# Default Lookback and Activity Window
DEFAULT_LOOKBACK_DAYS = 15
DEFAULT_ACTIVITY_WINDOW_DAYS = 90
MIN_LOOKBACK_DAYS = 3
MAX_LOOKBACK_DAYS = 16

DEFAULT_TOP_N_COUNT = 10
DEFAULT_TOP_N_RANKING_PERIOD_DAYS = 90  # e.g., rank based on credits in last 90 days

DEFAULT_CREDIT_THRESHOLD = 100
DEFAULT_CREDIT_PERIOD_DAYS = 30

# --- Multi-Account Analysis Configuration ---
MULTI_ACCOUNT_MAX_WORKERS = 8  # Fixed parallel processing threads
MULTI_ACCOUNT_DEFAULT_LOOKBACK_DAYS = 15  # Default lookback period
MULTI_ACCOUNT_RANKING_PERIOD_DAYS = 30  # Fixed ranking period
MULTI_ACCOUNT_DEFAULT_MIN_CREDITS = 500  # Default minimum credit threshold (last 30 days)
MULTI_ACCOUNT_DEFAULT_TOP_N_WAREHOUSES = 10  # Default Top N expensive warehouses per account


APP_DISCLAIMER_TEXT = """
---
**Important Consideration:**

This analysis and the recommendations provided are generated by an AI model based on the data supplied. They are intended to assist in identifying potential areas for warehouse optimization and should be carefully reviewed and validated by your internal technical teams before implementation. Snowflake and its Professional Services organization do not assume liability for any outcomes or consequences arising from actions taken based on these AI-generated suggestions.

"""


# --- App Environment Configuration ---
# This dictionary holds settings for different Snowflake accounts.
# The app will detect the current account and use the corresponding settings.
ACCOUNT_CONFIG = {
    "SNOWHOUSE": {
        "DB_NAME": "PST",
        "SCHEMA_NAME": "SVCS"
    },
    "DEFAULT": { # This will be used for any account that is not 'SNOWHOUSE'
        "DB_NAME": "SNOWFLAKE",
        "SCHEMA_NAME": "ACCOUNT_USAGE"
    }
}

# --- Audit Logging Configuration ---
AUDIT_LOGGING_ENABLED = True  # Set to False to disable audit logging
AUDIT_TABLE_CONFIG = {
    "DATABASE": "SNOWFLAKE360",
    "SCHEMA": "S360_ACCOUNT_INFO",
    "TABLE": "WAREHOUSE_PRISM_LOGGING"
}

# --- Database Configuration for warehouse analysis ---
WAREHOUSE_PRISM_DATABASE = "SNOWFLAKE360"
WAREHOUSE_PRISM_SCHEMA = "S360_ACCOUNT_INFO"
WAREHOUSE_PRISM_TABLE = "WAREHOUSE_PRISM"