ALL_DG_QUERIES = {

    "dg_health_score_data": """
WITH Get_Tables AS (
    SELECT object_id, object_database, object_schema, object_name,
           ANY_VALUE(TAG_NAME) AS HAS_TAG
    FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES tr
    WHERE tr.DOMAIN IN ('TABLE', 'COLUMN')
      AND tr.OBJECT_DELETED IS NULL
    GROUP BY object_id, object_database, object_schema, object_name
)
SELECT
    t.TABLE_CATALOG AS DATABASE_NAME,
    COUNT(*) AS TOTAL_TABLES,
    COUNT(DISTINCT CASE WHEN tr.HAS_TAG IS NOT NULL THEN t.TABLE_ID END) AS TAGGED_TABLES,
    COUNT(*) - COUNT(DISTINCT CASE WHEN tr.HAS_TAG IS NOT NULL THEN t.TABLE_ID END) AS UNTAGGED_TABLES,
    ROUND(COUNT(DISTINCT CASE WHEN tr.HAS_TAG IS NOT NULL THEN t.TABLE_ID END)
          / NULLIF(COUNT(*), 0) * 100, 2) AS COVERAGE_PCT
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES t
LEFT JOIN Get_Tables tr ON t.TABLE_ID = tr.OBJECT_ID
WHERE t.DELETED IS NULL
  AND t.TABLE_CATALOG != 'SNOWFLAKE'
  AND t.TABLE_SCHEMA != 'INFORMATION_SCHEMA'
GROUP BY t.TABLE_CATALOG
ORDER BY TOTAL_TABLES DESC
""",

    "dg_classification_data": """
WITH APM AS (
    SELECT $1 APPLY_METHOD FROM VALUES
        ('CLASSIFIED'), ('INHERITED'), ('MANUAL'), ('PROPAGATED'), ('NULL'), ('NONE')
),
VEW AS (
    SELECT COALESCE(APPLY_METHOD, 'NULL') AS APPLY_METHOD,
           COUNT(*) AS TOTAL_TAGS,
           COALESCE(COUNT(DISTINCT OBJECT_NAME), 0) AS OBJECTS_COVERED
    FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
    WHERE OBJECT_DELETED IS NULL
      AND OBJECT_DATABASE != 'SNOWFLAKE'
    GROUP BY 1
)
SELECT APM.APPLY_METHOD,
       COALESCE(VEW.TOTAL_TAGS, 0) AS TOTAL_TAGS,
       COALESCE(VEW.OBJECTS_COVERED, 0) AS OBJECTS_COVERED
FROM APM
LEFT OUTER JOIN VEW ON APM.APPLY_METHOD = VEW.APPLY_METHOD
""",

    "dg_policy_inventory_data": """
WITH SF AS (
    SELECT DISTINCT POLICY_KIND
    FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES
),
S360 AS (
    SELECT POLICY_KIND,
           COUNT(*) AS ACTIVE_COUNT
    FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES
    WHERE POLICY_STATUS = 'ACTIVE'
      AND POLICY_DB != 'SNOWFLAKE'
    GROUP BY 1
)
SELECT SF.POLICY_KIND,
       NVL(S360.ACTIVE_COUNT, 0) AS ACTIVE_COUNT
FROM SF
LEFT OUTER JOIN S360 ON SF.POLICY_KIND = S360.POLICY_KIND
ORDER BY 1, 2
""",

    "dg_sensitivity_heatmap": """
SELECT
    TAG_VALUE AS sensitivity_level,
    COUNT(*) AS object_count
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE OBJECT_DELETED IS NULL
  AND OBJECT_DATABASE != 'SNOWFLAKE'
  AND TAG_NAME ILIKE '%SENSITIVITY%'
GROUP BY TAG_VALUE
ORDER BY object_count DESC
""",

    "dg_tagging_audit_data": """
SELECT
    t.TABLE_CATALOG AS database_name,
    t.TABLE_SCHEMA AS schema_name,
    t.TABLE_NAME,
    t.TABLE_TYPE,
    CASE
        WHEN tr.TAG_NAME IS NULL THEN 'Untagged'
        ELSE 'Tagged: ' || tr.TAG_NAME
    END AS tag_status,
    tr.TAG_VALUE,
    tr.APPLY_METHOD
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES t
LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES tr
    ON t.TABLE_ID = tr.OBJECT_ID
    AND tr.DOMAIN IN ('TABLE', 'COLUMN', 'DATABASE', 'SCHEMA', 'SHARE')
    AND tr.OBJECT_DELETED IS NULL
WHERE t.DELETED IS NULL
    AND t.TABLE_CATALOG != 'SNOWFLAKE'
    AND t.TABLE_SCHEMA != 'INFORMATION_SCHEMA'
    AND tag_value IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY t.TABLE_ID ORDER BY tr.TAG_NAME NULLS LAST) = 1
ORDER BY tag_status ASC
""",

    "dg_sensitive_tagged": """
SELECT
    OBJECT_DATABASE AS database_name,
    OBJECT_SCHEMA AS schema_name,
    OBJECT_NAME AS table_name,
    COLUMN_NAME,
    TAG_NAME,
    TAG_VALUE,
    APPLY_METHOD
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE DOMAIN = 'COLUMN'
  AND OBJECT_DELETED IS NULL
  AND OBJECT_DATABASE != 'SNOWFLAKE'
  AND (
    TAG_NAME ILIKE '%PII%'        OR TAG_NAME ILIKE '%PHI%'        OR
    TAG_NAME ILIKE '%PCI%'        OR TAG_NAME ILIKE '%HIPAA%'      OR
    TAG_NAME ILIKE '%GDPR%'       OR TAG_NAME ILIKE '%SENSIT%'     OR
    TAG_NAME ILIKE '%CONFIDENT%'  OR TAG_NAME ILIKE '%RESTRICT%'   OR
    TAG_NAME ILIKE '%PRIVAC%'     OR TAG_NAME ILIKE '%SECURIT%'    OR
    TAG_NAME ILIKE '%MASK%'       OR TAG_NAME ILIKE '%CLASSIF%'    OR
    TAG_NAME ILIKE '%DATA_CLASS%' OR TAG_NAME ILIKE '%DATA_SENS%'  OR
    TAG_VALUE ILIKE '%PII%'       OR TAG_VALUE ILIKE '%SENSITIVE%' OR
    TAG_VALUE ILIKE '%CONFIDENTIAL%'
  )
ORDER BY database_name, table_name, COLUMN_NAME
LIMIT 500
""",

    "dg_stale_tagged": """
SELECT
    t.TABLE_CATALOG AS database_name,
    t.TABLE_SCHEMA AS schema_name,
    t.TABLE_NAME,
    tr.TAG_NAME,
    tr.TAG_VALUE,
    t.LAST_ALTERED,
    DATEDIFF('day', t.LAST_ALTERED, CURRENT_TIMESTAMP()) AS days_since_modified
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES t
INNER JOIN SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES tr
    ON t.TABLE_CATALOG = tr.OBJECT_DATABASE
   AND t.TABLE_SCHEMA  = tr.OBJECT_SCHEMA
   AND t.TABLE_NAME    = tr.OBJECT_NAME
   AND tr.DOMAIN = 'TABLE'
   AND tr.OBJECT_DELETED IS NULL
WHERE t.LAST_ALTERED < DATEADD('day', -90, CURRENT_TIMESTAMP())
  AND t.DELETED IS NULL
  AND t.TABLE_CATALOG != 'SNOWFLAKE'
  AND t.TABLE_SCHEMA != 'INFORMATION_SCHEMA'
ORDER BY t.LAST_ALTERED ASC
LIMIT 200
""",

    "dg_dangling_tags": """
SELECT
    TAG_DATABASE, TAG_SCHEMA, TAG_NAME, TAG_VALUE,
    OBJECT_DATABASE, OBJECT_SCHEMA, OBJECT_NAME, DOMAIN,
    OBJECT_DELETED
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE OBJECT_DELETED IS NOT NULL
  AND OBJECT_DATABASE != 'SNOWFLAKE'
ORDER BY OBJECT_DELETED DESC
LIMIT 200
""",

    "dg_heavy_column_tagging": """
SELECT
    OBJECT_DATABASE AS database_name,
    OBJECT_SCHEMA AS schema_name,
    OBJECT_NAME AS table_name,
    COUNT(*) AS column_tag_count,
    COUNT(DISTINCT COLUMN_NAME) AS distinct_columns_tagged,
    COUNT(DISTINCT TAG_NAME) AS distinct_tag_types
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE DOMAIN = 'COLUMN'
  AND OBJECT_DELETED IS NULL
  AND OBJECT_DATABASE != 'SNOWFLAKE'
GROUP BY OBJECT_DATABASE, OBJECT_SCHEMA, OBJECT_NAME
ORDER BY column_tag_count DESC
LIMIT 30
""",

    "dg_tags_no_allowed_values": """
SELECT
    TAG_DATABASE, TAG_SCHEMA, TAG_NAME,
    COUNT(DISTINCT TAG_VALUE) AS distinct_values,
    COUNT(*) AS total_references,
    LISTAGG(DISTINCT TAG_VALUE, ', ') WITHIN GROUP (ORDER BY TAG_VALUE) AS sample_values
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE OBJECT_DELETED IS NULL
  AND OBJECT_DATABASE != 'SNOWFLAKE'
GROUP BY TAG_DATABASE, TAG_SCHEMA, TAG_NAME
HAVING COUNT(DISTINCT TAG_VALUE) > 10
ORDER BY distinct_values DESC
""",

    "dg_share_tag": """
SELECT
    TAG_DATABASE,
    TAG_SCHEMA,
    TAG_NAME,
    TAG_VALUE,
    OBJECT_DATABASE,
    OBJECT_SCHEMA,
    OBJECT_NAME,
    DOMAIN,
    APPLY_METHOD
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE DOMAIN = 'SHARE'
    AND OBJECT_DELETED IS NULL
""",

    "dg_rap": """
SELECT
    POLICY_DB,
    POLICY_SCHEMA,
    POLICY_NAME,
    REF_DATABASE_NAME AS PROTECTED_DB,
    REF_SCHEMA_NAME AS PROTECTED_SCHEMA,
    REF_ENTITY_NAME AS PROTECTED_TABLE,
    REF_ENTITY_DOMAIN AS OBJECT_TYPE
FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES
WHERE POLICY_KIND = 'ROW_ACCESS_POLICY'
    AND POLICY_STATUS = 'ACTIVE'
    AND POLICY_DB != 'SNOWFLAKE'
ORDER BY POLICY_DB, POLICY_NAME
""",

    "dg_unprotected": """
SELECT t.TABLE_CATALOG AS DATABASE_NAME,
       t.TABLE_SCHEMA AS SCHEMA_NAME,
       t.TABLE_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES t
LEFT JOIN (
    SELECT DISTINCT REF_DATABASE_NAME, REF_SCHEMA_NAME, REF_ENTITY_NAME
    FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES
    WHERE POLICY_KIND = 'ROW_ACCESS_POLICY'
        AND POLICY_STATUS = 'ACTIVE'
        AND POLICY_DB != 'SNOWFLAKE'
) rap ON t.TABLE_CATALOG = rap.REF_DATABASE_NAME
    AND t.TABLE_SCHEMA = rap.REF_SCHEMA_NAME
    AND t.TABLE_NAME = rap.REF_ENTITY_NAME
WHERE rap.REF_ENTITY_NAME IS NULL
    AND t.DELETED IS NULL
    AND t.TABLE_CATALOG NOT IN ('SNOWFLAKE', 'SNOWFLAKE_SAMPLE_DATA')
    AND t.TABLE_SCHEMA != 'INFORMATION_SCHEMA'
ORDER BY t.TABLE_CATALOG, t.TABLE_SCHEMA, t.TABLE_NAME
""",

    "dg_masking_coverage": """
WITH sensitive_columns AS (
    SELECT DISTINCT
        OBJECT_DATABASE AS database_name,
        OBJECT_SCHEMA   AS schema_name,
        OBJECT_NAME     AS table_name,
        COLUMN_NAME,
        'SENSITIVE_TAG'  AS detection_method
    FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
    WHERE DOMAIN = 'COLUMN'
      AND OBJECT_DELETED IS NULL
      AND OBJECT_DATABASE != 'SNOWFLAKE'
      AND (
        TAG_NAME ILIKE '%PII%'        OR TAG_NAME ILIKE '%PHI%'       OR
        TAG_NAME ILIKE '%PCI%'        OR TAG_NAME ILIKE '%GDPR%'      OR
        TAG_NAME ILIKE '%SENSIT%'     OR TAG_NAME ILIKE '%CONFIDENT%' OR
        TAG_NAME ILIKE '%PRIVAC%'     OR TAG_NAME ILIKE '%MASK%'      OR
        TAG_NAME ILIKE '%CLASSIF%'    OR TAG_NAME ILIKE '%DATA_CLASS%'OR
        TAG_VALUE ILIKE '%PII%'       OR TAG_VALUE ILIKE '%SENSITIVE%' OR
        TAG_VALUE ILIKE '%CONFIDENTIAL%'
      )
),
masked_columns AS (
    SELECT DISTINCT
        REF_DATABASE_NAME AS database_name,
        REF_SCHEMA_NAME   AS schema_name,
        REF_ENTITY_NAME   AS table_name,
        REF_COLUMN_NAME   AS COLUMN_NAME,
        'MASKING_POLICY'  AS detection_method
    FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES
    WHERE POLICY_KIND = 'MASKING_POLICY'
      AND REF_DATABASE_NAME != 'SNOWFLAKE'
),
all_sensitive AS (
    SELECT database_name, schema_name, table_name, COLUMN_NAME, detection_method FROM sensitive_columns
    UNION
    SELECT database_name, schema_name, table_name, COLUMN_NAME, detection_method FROM masked_columns
),
coverage AS (
    SELECT
        a.database_name, a.schema_name, a.table_name, a.COLUMN_NAME,
        MAX(CASE WHEN a.detection_method = 'SENSITIVE_TAG' THEN 1 ELSE 0 END) AS has_sensitive_tag,
        MAX(CASE WHEN a.detection_method = 'MASKING_POLICY' THEN 1 ELSE 0 END) AS has_masking_policy
    FROM all_sensitive a
    GROUP BY 1, 2, 3, 4
)
SELECT
    database_name, schema_name, table_name, COLUMN_NAME,
    has_sensitive_tag, has_masking_policy,
    CASE
        WHEN has_sensitive_tag = 1 AND has_masking_policy = 1 THEN 'Protected (Tag + Mask)'
        WHEN has_sensitive_tag = 0 AND has_masking_policy = 1 THEN 'Masked (No Sensitive Tag)'
        WHEN has_sensitive_tag = 1 AND has_masking_policy = 0 THEN 'UNPROTECTED - Sensitive but No Mask'
        ELSE 'Unknown'
    END AS protection_status
FROM coverage
ORDER BY has_masking_policy ASC, database_name, table_name, COLUMN_NAME
LIMIT 500
""",

    "dg_dangling_policies": """
SELECT
    pr.POLICY_KIND,
    pr.POLICY_DB,
    pr.POLICY_SCHEMA,
    pr.POLICY_NAME,
    pr.REF_DATABASE_NAME,
    pr.REF_SCHEMA_NAME,
    pr.REF_ENTITY_NAME,
    pr.REF_ENTITY_DOMAIN,
    'POTENTIALLY_DANGLING' AS status
FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES pr
LEFT JOIN SNOWFLAKE.ACCOUNT_USAGE.TABLES t
    ON pr.REF_DATABASE_NAME = t.TABLE_CATALOG
    AND pr.REF_SCHEMA_NAME = t.TABLE_SCHEMA
    AND pr.REF_ENTITY_NAME = t.TABLE_NAME
    AND t.DELETED IS NULL
WHERE pr.POLICY_STATUS = 'ACTIVE'
  AND pr.POLICY_DB != 'SNOWFLAKE'
  AND t.TABLE_ID IS NULL
ORDER BY pr.POLICY_KIND, pr.POLICY_NAME
LIMIT 100
""",

    "dg_masking_design": """
SELECT
    POLICY_DB,
    POLICY_SCHEMA,
    POLICY_NAME,
    COUNT(DISTINCT REF_ENTITY_NAME) AS tables_protected,
    COUNT(DISTINCT REF_COLUMN_NAME) AS columns_protected,
    COUNT(*) AS total_references
FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES
WHERE POLICY_KIND = 'MASKING_POLICY'
  AND POLICY_STATUS = 'ACTIVE'
  AND POLICY_DB != 'SNOWFLAKE'
GROUP BY POLICY_DB, POLICY_SCHEMA, POLICY_NAME
ORDER BY total_references DESC
LIMIT 30
""",

    "dg_downstream_unmasked": """
WITH sensitive_cols AS (
    SELECT DISTINCT
        OBJECT_DATABASE, OBJECT_SCHEMA, OBJECT_NAME, COLUMN_NAME, TAG_NAME, TAG_VALUE
    FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
    WHERE DOMAIN = 'COLUMN'
      AND OBJECT_DELETED IS NULL
      AND OBJECT_DATABASE != 'SNOWFLAKE'
      AND (TAG_NAME ILIKE '%PII%' OR TAG_NAME ILIKE '%SENSITIVE%'
           OR TAG_VALUE ILIKE '%SENSITIVE%' OR TAG_VALUE ILIKE '%CONFIDENTIAL%')
),
masked_cols AS (
    SELECT DISTINCT
        REF_DATABASE_NAME, REF_SCHEMA_NAME, REF_ENTITY_NAME, REF_COLUMN_NAME
    FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES
    WHERE POLICY_KIND = 'MASKING_POLICY'
      AND POLICY_STATUS = 'ACTIVE'
)
SELECT
    sc.OBJECT_DATABASE AS database_name,
    sc.OBJECT_SCHEMA AS schema_name,
    sc.OBJECT_NAME AS table_name,
    sc.COLUMN_NAME,
    sc.TAG_NAME,
    sc.TAG_VALUE,
    CASE WHEN mc.REF_COLUMN_NAME IS NULL THEN 'UNMASKED' ELSE 'MASKED' END AS mask_status
FROM sensitive_cols sc
LEFT JOIN masked_cols mc
    ON sc.OBJECT_DATABASE = mc.REF_DATABASE_NAME
    AND sc.OBJECT_SCHEMA = mc.REF_SCHEMA_NAME
    AND sc.OBJECT_NAME = mc.REF_ENTITY_NAME
    AND sc.COLUMN_NAME = mc.REF_COLUMN_NAME
WHERE mc.REF_COLUMN_NAME IS NULL
ORDER BY sc.OBJECT_DATABASE, sc.OBJECT_NAME
LIMIT 200
""",

    "dg_sensitive_access": """
WITH sensitive_objects AS (
    SELECT DISTINCT OBJECT_DATABASE, OBJECT_SCHEMA, OBJECT_NAME
    FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
    WHERE OBJECT_DELETED IS NULL
      AND OBJECT_DATABASE != 'SNOWFLAKE'
      AND DOMAIN IN ('TABLE','VIEW','COLUMN')
      AND (
        TAG_NAME ILIKE '%PII%'        OR TAG_NAME ILIKE '%PHI%'        OR
        TAG_NAME ILIKE '%PCI%'        OR TAG_NAME ILIKE '%HIPAA%'      OR
        TAG_NAME ILIKE '%GDPR%'       OR TAG_NAME ILIKE '%SENSIT%'     OR
        TAG_NAME ILIKE '%CONFIDENT%'  OR TAG_NAME ILIKE '%RESTRICT%'   OR
        TAG_NAME ILIKE '%PRIVAC%'     OR TAG_NAME ILIKE '%SECURIT%'    OR
        TAG_NAME ILIKE '%MASK%'       OR TAG_NAME ILIKE '%CLASSIF%'    OR
        TAG_NAME ILIKE '%DATA_CLASS%' OR TAG_NAME ILIKE '%DATA_SENS%'
        OR TAG_VALUE ILIKE '%PII%' OR TAG_VALUE ILIKE '%PHI%' OR
        TAG_VALUE ILIKE '%SENSITIVE%' OR TAG_VALUE ILIKE '%CONFIDENTIAL%' OR
        TAG_VALUE ILIKE '%RESTRICTED%' OR TAG_VALUE ILIKE '%SECRET%' OR
        TAG_VALUE ILIKE '%PRIVATE%'
      )
),
user_sensitive_access AS (
    SELECT
        ah.USER_NAME,
        f.value:objectDatabase::STRING AS obj_db,
        f.value:objectSchema::STRING   AS obj_schema,
        f.value:objectName::STRING     AS obj_name,
        ah.QUERY_ID
    FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY ah,
    LATERAL FLATTEN(input => ah.BASE_OBJECTS_ACCESSED) f
    JOIN sensitive_objects so
      ON so.OBJECT_DATABASE = f.value:objectDatabase::STRING
     AND so.OBJECT_SCHEMA   = f.value:objectSchema::STRING
     AND so.OBJECT_NAME     = f.value:objectName::STRING
    WHERE ah.QUERY_START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
)
SELECT
    USER_NAME,
    COUNT(DISTINCT QUERY_ID) AS sensitive_access_count,
    COUNT(DISTINCT obj_db || '.' || obj_schema || '.' || obj_name) AS distinct_objects_accessed
FROM user_sensitive_access
GROUP BY USER_NAME
ORDER BY sensitive_access_count DESC
LIMIT 50
""",

    "dg_downstream_deps": """
WITH sensitive_objects AS (
    SELECT DISTINCT OBJECT_DATABASE, OBJECT_SCHEMA, OBJECT_NAME, DOMAIN AS OBJECT_DOMAIN
    FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
    WHERE OBJECT_DELETED IS NULL
      AND OBJECT_DATABASE <> 'SNOWFLAKE'
      AND DOMAIN IN ('TABLE','VIEW')
      AND (
        TAG_NAME ILIKE '%PII%'        OR TAG_NAME ILIKE '%PHI%'        OR
        TAG_NAME ILIKE '%PCI%'        OR TAG_NAME ILIKE '%HIPAA%'      OR
        TAG_NAME ILIKE '%GDPR%'       OR TAG_NAME ILIKE '%SENSIT%'     OR
        TAG_NAME ILIKE '%CONFIDENT%'  OR TAG_NAME ILIKE '%RESTRICT%'   OR
        TAG_NAME ILIKE '%PRIVAC%'     OR TAG_NAME ILIKE '%SECURIT%'    OR
        TAG_NAME ILIKE '%MASK%'       OR TAG_NAME ILIKE '%CLASSIF%'    OR
        TAG_NAME ILIKE '%DATA_CLASS%' OR TAG_NAME ILIKE '%DATA_SENS%'
        OR TAG_VALUE ILIKE '%PII%' OR TAG_VALUE ILIKE '%PHI%' OR
        TAG_VALUE ILIKE '%SENSITIVE%' OR TAG_VALUE ILIKE '%CONFIDENTIAL%' OR
        TAG_VALUE ILIKE '%RESTRICTED%' OR TAG_VALUE ILIKE '%SECRET%' OR
        TAG_VALUE ILIKE '%PRIVATE%'
      )
),
lineage AS (
    SELECT
        od.REFERENCED_DATABASE,
        od.REFERENCED_SCHEMA,
        od.REFERENCED_OBJECT_NAME,
        od.REFERENCED_OBJECT_DOMAIN,
        od.REFERENCING_DATABASE,
        od.REFERENCING_SCHEMA,
        od.REFERENCING_OBJECT_NAME,
        od.REFERENCING_OBJECT_DOMAIN
    FROM SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES od
    JOIN sensitive_objects s
      ON s.OBJECT_DATABASE = od.REFERENCED_DATABASE
     AND s.OBJECT_SCHEMA   = od.REFERENCED_SCHEMA
     AND s.OBJECT_NAME     = od.REFERENCED_OBJECT_NAME
    WHERE od.REFERENCED_DATABASE <> 'SNOWFLAKE'
)
SELECT * FROM lineage
ORDER BY REFERENCED_DATABASE, REFERENCED_SCHEMA, REFERENCED_OBJECT_NAME,
         REFERENCING_DATABASE, REFERENCING_SCHEMA, REFERENCING_OBJECT_NAME
""",

    "dg_tag_assignments_by_domain": """
SELECT
    DOMAIN,
    COUNT(*) AS ASSIGNMENT_COUNT
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE OBJECT_DELETED IS NULL
  AND OBJECT_DATABASE != 'SNOWFLAKE'
GROUP BY DOMAIN
ORDER BY ASSIGNMENT_COUNT DESC
""",

    "dg_top_tag_names": """
SELECT
    TAG_NAME,
    COUNT(*) AS ASSIGNMENT_COUNT
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE OBJECT_DELETED IS NULL
  AND OBJECT_DATABASE != 'SNOWFLAKE'
GROUP BY TAG_NAME
ORDER BY ASSIGNMENT_COUNT DESC
LIMIT 20
""",

    "dg_masking_coverage_detail": """
WITH sensitive_tag_cols AS (
    SELECT DISTINCT
        OBJECT_DATABASE, OBJECT_SCHEMA, OBJECT_NAME, COLUMN_NAME,
        MIN(TAG_NAME) AS TAG_NAME,
        MIN(TAG_VALUE) AS TAG_VALUE
    FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
    WHERE DOMAIN = 'COLUMN'
      AND OBJECT_DELETED IS NULL
      AND OBJECT_DATABASE != 'SNOWFLAKE'
      AND (
        TAG_NAME ILIKE '%PII%'        OR TAG_NAME ILIKE '%PHI%'        OR
        TAG_NAME ILIKE '%PCI%'        OR TAG_NAME ILIKE '%HIPAA%'      OR
        TAG_NAME ILIKE '%GDPR%'       OR TAG_NAME ILIKE '%SENSIT%'     OR
        TAG_NAME ILIKE '%CONFIDENT%'  OR TAG_NAME ILIKE '%RESTRICT%'   OR
        TAG_NAME ILIKE '%PRIVAC%'     OR TAG_NAME ILIKE '%SECURIT%'    OR
        TAG_NAME ILIKE '%MASK%'       OR TAG_NAME ILIKE '%CLASSIF%'    OR
        TAG_NAME ILIKE '%DATA_CLASS%' OR TAG_NAME ILIKE '%DATA_SENS%'
        OR
        TAG_VALUE ILIKE '%PII%'        OR TAG_VALUE ILIKE '%PHI%'       OR
        TAG_VALUE ILIKE '%PCI%'        OR TAG_VALUE ILIKE '%SSN%'       OR
        TAG_VALUE ILIKE '%SENSITIVE%'  OR TAG_VALUE ILIKE '%CONFIDENT%' OR
        TAG_VALUE ILIKE '%RESTRICTED%' OR TAG_VALUE ILIKE '%SECRET%'    OR
        TAG_VALUE ILIKE '%PRIVATE%'
      )
    GROUP BY OBJECT_DATABASE, OBJECT_SCHEMA, OBJECT_NAME, COLUMN_NAME
),
masked_cols AS (
    SELECT DISTINCT
        REF_DATABASE_NAME AS OBJECT_DATABASE,
        REF_SCHEMA_NAME AS OBJECT_SCHEMA,
        REF_ENTITY_NAME AS OBJECT_NAME,
        REF_COLUMN_NAME AS COLUMN_NAME,
        MIN(POLICY_NAME) AS POLICY_NAME
    FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES
    WHERE POLICY_KIND = 'MASKING_POLICY'
      AND POLICY_STATUS = 'ACTIVE'
      AND REF_DATABASE_NAME != 'SNOWFLAKE'
    GROUP BY REF_DATABASE_NAME, REF_SCHEMA_NAME, REF_ENTITY_NAME, REF_COLUMN_NAME
),
combined AS (
    SELECT OBJECT_DATABASE, OBJECT_SCHEMA, OBJECT_NAME, COLUMN_NAME FROM sensitive_tag_cols
    UNION
    SELECT OBJECT_DATABASE, OBJECT_SCHEMA, OBJECT_NAME, COLUMN_NAME FROM masked_cols
)
SELECT
    c.OBJECT_DATABASE AS DATABASE_NAME,
    c.OBJECT_SCHEMA AS SCHEMA_NAME,
    c.OBJECT_NAME AS TABLE_NAME,
    c.COLUMN_NAME,
    s.TAG_NAME,
    s.TAG_VALUE,
    COALESCE(m.POLICY_NAME, 'UNPROTECTED') AS POLICY_NAME,
    CASE WHEN m.POLICY_NAME IS NULL THEN 'UNPROTECTED' ELSE 'PROTECTED' END AS PROTECTION_STATUS
FROM combined c
LEFT JOIN sensitive_tag_cols s
    ON c.OBJECT_DATABASE = s.OBJECT_DATABASE
   AND c.OBJECT_SCHEMA = s.OBJECT_SCHEMA
   AND c.OBJECT_NAME = s.OBJECT_NAME
   AND c.COLUMN_NAME = s.COLUMN_NAME
LEFT JOIN masked_cols m
    ON c.OBJECT_DATABASE = m.OBJECT_DATABASE
   AND c.OBJECT_SCHEMA = m.OBJECT_SCHEMA
   AND c.OBJECT_NAME = m.OBJECT_NAME
   AND c.COLUMN_NAME = m.COLUMN_NAME
ORDER BY PROTECTION_STATUS ASC, DATABASE_NAME, TABLE_NAME, COLUMN_NAME
LIMIT 500
""",

    "dg_masking_policy_patterns": """
SELECT
    POLICY_DB,
    POLICY_SCHEMA,
    POLICY_NAME,
    CASE
        WHEN POLICY_NAME ILIKE '%HASH%' OR POLICY_NAME ILIKE '%SHA%' OR POLICY_NAME ILIKE '%MD5%'
            THEN 'HASHING'
        WHEN POLICY_NAME ILIKE '%NULL%' OR POLICY_NAME ILIKE '%NULLIF%'
            THEN 'NULLIFY'
        WHEN POLICY_NAME ILIKE '%STATE%' OR POLICY_NAME ILIKE '%ZIP%' OR POLICY_NAME ILIKE '%BAND%'
          OR POLICY_NAME ILIKE '%BUCKET%' OR POLICY_NAME ILIKE '%DOB%' OR POLICY_NAME ILIKE '%RANGE%'
          OR POLICY_NAME ILIKE '%BANDING%'
            THEN 'BANDING / BUCKETING'
        ELSE 'OTHER'
    END AS MASKING_PATTERN,
    '' AS POLICY_SIGNATURE
FROM (
    SELECT DISTINCT POLICY_DB, POLICY_SCHEMA, POLICY_NAME
    FROM SNOWFLAKE.ACCOUNT_USAGE.POLICY_REFERENCES
    WHERE POLICY_KIND = 'MASKING_POLICY'
      AND POLICY_DB != 'SNOWFLAKE'
) p
ORDER BY MASKING_PATTERN, POLICY_DB, POLICY_SCHEMA, POLICY_NAME
""",

    "dg_dangling_gov_tags_by_db": """
WITH all_gov_tags AS (
    SELECT DISTINCT TAG_DATABASE, TAG_SCHEMA, TAG_NAME
    FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
    WHERE OBJECT_DATABASE != 'SNOWFLAKE'
      AND (
        TAG_NAME ILIKE '%PII%'        OR TAG_NAME ILIKE '%PHI%'        OR
        TAG_NAME ILIKE '%PCI%'        OR TAG_NAME ILIKE '%HIPAA%'      OR
        TAG_NAME ILIKE '%GDPR%'       OR TAG_NAME ILIKE '%SENSIT%'     OR
        TAG_NAME ILIKE '%CONFIDENT%'  OR TAG_NAME ILIKE '%RESTRICT%'   OR
        TAG_NAME ILIKE '%PRIVAC%'     OR TAG_NAME ILIKE '%SECURIT%'    OR
        TAG_NAME ILIKE '%MASK%'       OR TAG_NAME ILIKE '%CLASSIF%'    OR
        TAG_NAME ILIKE '%DATA_CLASS%' OR TAG_NAME ILIKE '%DATA_SENS%'
      )
),
live_refs AS (
    SELECT DISTINCT TAG_DATABASE, TAG_SCHEMA, TAG_NAME
    FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
    WHERE OBJECT_DELETED IS NULL
      AND OBJECT_DATABASE != 'SNOWFLAKE'
      AND (
        TAG_NAME ILIKE '%PII%'        OR TAG_NAME ILIKE '%PHI%'        OR
        TAG_NAME ILIKE '%PCI%'        OR TAG_NAME ILIKE '%HIPAA%'      OR
        TAG_NAME ILIKE '%GDPR%'       OR TAG_NAME ILIKE '%SENSIT%'     OR
        TAG_NAME ILIKE '%CONFIDENT%'  OR TAG_NAME ILIKE '%RESTRICT%'   OR
        TAG_NAME ILIKE '%PRIVAC%'     OR TAG_NAME ILIKE '%SECURIT%'    OR
        TAG_NAME ILIKE '%MASK%'       OR TAG_NAME ILIKE '%CLASSIF%'    OR
        TAG_NAME ILIKE '%DATA_CLASS%' OR TAG_NAME ILIKE '%DATA_SENS%'
      )
)
SELECT a.TAG_DATABASE AS DATABASE_NAME, COUNT(*) AS DANGLING_TAGS
FROM all_gov_tags a
LEFT JOIN live_refs l
    ON a.TAG_DATABASE = l.TAG_DATABASE
   AND a.TAG_SCHEMA = l.TAG_SCHEMA
   AND a.TAG_NAME = l.TAG_NAME
WHERE l.TAG_NAME IS NULL
GROUP BY a.TAG_DATABASE
ORDER BY DANGLING_TAGS DESC
""",

    "dg_boolean_like_tags_columns": """
WITH column_tag_stats AS (
    SELECT
        OBJECT_DATABASE, OBJECT_SCHEMA, OBJECT_NAME, COLUMN_NAME,
        COUNT(DISTINCT TAG_NAME) AS TAG_COUNT,
        SUM(CASE WHEN LOWER(TAG_VALUE) IN ('true','false','t','f','y','n','yes','no','1','0') THEN 1 ELSE 0 END) AS BOOLEAN_LIKE_TAG_COUNT
    FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
    WHERE DOMAIN = 'COLUMN'
      AND OBJECT_DELETED IS NULL
      AND OBJECT_DATABASE != 'SNOWFLAKE'
      AND (
        TAG_NAME ILIKE '%PII%'        OR TAG_NAME ILIKE '%PHI%'        OR
        TAG_NAME ILIKE '%PCI%'        OR TAG_NAME ILIKE '%HIPAA%'      OR
        TAG_NAME ILIKE '%GDPR%'       OR TAG_NAME ILIKE '%SENSIT%'     OR
        TAG_NAME ILIKE '%CONFIDENT%'  OR TAG_NAME ILIKE '%RESTRICT%'   OR
        TAG_NAME ILIKE '%PRIVAC%'     OR TAG_NAME ILIKE '%SECURIT%'    OR
        TAG_NAME ILIKE '%MASK%'       OR TAG_NAME ILIKE '%CLASSIF%'    OR
        TAG_NAME ILIKE '%DATA_CLASS%' OR TAG_NAME ILIKE '%DATA_SENS%'
      )
    GROUP BY 1, 2, 3, 4
)
SELECT *
FROM column_tag_stats
WHERE BOOLEAN_LIKE_TAG_COUNT <= 3 AND TAG_COUNT > 2
ORDER BY BOOLEAN_LIKE_TAG_COUNT DESC, TAG_COUNT DESC
""",

    "dg_boolean_governance_tags": """
SELECT
    TAG_NAME,
    COUNT(*) AS ASSIGNMENTS,
    COUNT(DISTINCT TAG_VALUE) AS DISTINCT_VALUES,
    COUNT(DISTINCT CASE WHEN DOMAIN = 'COLUMN' THEN OBJECT_ID END) AS COLUMNS_TAGGED,
    SUM(CASE WHEN LOWER(TAG_VALUE) IN ('true','false','t','f','y','n','yes','no','1','0') THEN 1 ELSE 0 END) AS BOOLEAN_ASSIGNMENTS
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE OBJECT_DELETED IS NULL
  AND (
    TAG_NAME ILIKE '%PII%'        OR TAG_NAME ILIKE '%PHI%'        OR
    TAG_NAME ILIKE '%PCI%'        OR TAG_NAME ILIKE '%HIPAA%'      OR
    TAG_NAME ILIKE '%GDPR%'       OR TAG_NAME ILIKE '%SENSIT%'     OR
    TAG_NAME ILIKE '%CONFIDENT%'  OR TAG_NAME ILIKE '%RESTRICT%'   OR
    TAG_NAME ILIKE '%PRIVAC%'     OR TAG_NAME ILIKE '%SECURIT%'    OR
    TAG_NAME ILIKE '%MASK%'       OR TAG_NAME ILIKE '%CLASSIF%'    OR
    TAG_NAME ILIKE '%DATA_CLASS%' OR TAG_NAME ILIKE '%DATA_SENS%'
  )
GROUP BY TAG_NAME
HAVING BOOLEAN_ASSIGNMENTS > 0
ORDER BY BOOLEAN_ASSIGNMENTS DESC
""",

    "dg_tag_allowed_values_audit": """
SELECT
    TAG_DATABASE,
    TAG_SCHEMA,
    TAG_NAME,
    CASE
        WHEN COUNT(DISTINCT TAG_VALUE) = 0 OR MAX(TAG_VALUE) IS NULL THEN 'None'
        WHEN COUNT(DISTINCT TAG_VALUE) <= 8 THEN
            '[ ' || LISTAGG(DISTINCT '"' || TAG_VALUE || '"', ', ') WITHIN GROUP (ORDER BY TAG_VALUE) || ' ]'
        ELSE 'None (' || COUNT(DISTINCT TAG_VALUE)::VARCHAR || ' distinct values)'
    END AS ALLOWED_VALUES
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE OBJECT_DELETED IS NULL
  AND OBJECT_DATABASE != 'SNOWFLAKE'
  AND (
    TAG_NAME ILIKE '%PII%'        OR TAG_NAME ILIKE '%PHI%'        OR
    TAG_NAME ILIKE '%PCI%'        OR TAG_NAME ILIKE '%HIPAA%'      OR
    TAG_NAME ILIKE '%GDPR%'       OR TAG_NAME ILIKE '%SENSIT%'     OR
    TAG_NAME ILIKE '%CONFIDENT%'  OR TAG_NAME ILIKE '%RESTRICT%'   OR
    TAG_NAME ILIKE '%PRIVAC%'     OR TAG_NAME ILIKE '%SECURIT%'    OR
    TAG_NAME ILIKE '%MASK%'       OR TAG_NAME ILIKE '%CLASSIF%'    OR
    TAG_NAME ILIKE '%DATA_CLASS%' OR TAG_NAME ILIKE '%DATA_SENS%'
  )
GROUP BY TAG_DATABASE, TAG_SCHEMA, TAG_NAME
ORDER BY TAG_NAME
""",

    "dg_gov_tags_in_use": """
SELECT
    TAG_NAME,
    COUNT(*) AS ASSIGNMENTS
FROM SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES
WHERE OBJECT_DELETED IS NULL
  AND (
    TAG_NAME ILIKE '%PII%'        OR TAG_NAME ILIKE '%PHI%'        OR
    TAG_NAME ILIKE '%PCI%'        OR TAG_NAME ILIKE '%HIPAA%'      OR
    TAG_NAME ILIKE '%GDPR%'       OR TAG_NAME ILIKE '%SENSIT%'     OR
    TAG_NAME ILIKE '%CONFIDENT%'  OR TAG_NAME ILIKE '%RESTRICT%'   OR
    TAG_NAME ILIKE '%PRIVAC%'     OR TAG_NAME ILIKE '%SECURIT%'    OR
    TAG_NAME ILIKE '%MASK%'       OR TAG_NAME ILIKE '%CLASSIF%'    OR
    TAG_NAME ILIKE '%DATA_CLASS%' OR TAG_NAME ILIKE '%DATA_SENS%'
  )
GROUP BY TAG_NAME
ORDER BY ASSIGNMENTS DESC
""",

}
